# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 6) do

  create_table "accounts", :force => true do |t|
    t.column "user_id",     :integer
    t.column "type",        :string
    t.column "username",    :string,   :limit => 20
    t.column "password",    :string,   :limit => 20
    t.column "host",        :string,   :limit => 100
    t.column "token",       :text
    t.column "items_count", :integer,                 :default => 0
    t.column "updated_at",  :datetime
  end

  add_index "accounts", ["user_id", "type", "items_count", "updated_at"], :name => "index"

  create_table "cachedalbums", :force => true do |t|
    t.column "artist", :string
    t.column "title",  :string
    t.column "album",  :text
  end

  create_table "items", :force => true do |t|
    t.column "account_id", :integer
    t.column "type",       :string
    t.column "time",       :datetime
    t.column "data_id",    :string
    t.column "data",       :text
    t.column "complete",   :boolean,  :default => false
  end

  add_index "items", ["account_id", "type"], :name => "index_items_on_account_id_and_type"

  create_table "open_id_authentication_associations", :force => true do |t|
    t.column "server_url", :binary
    t.column "handle",     :string
    t.column "secret",     :binary
    t.column "issued",     :integer
    t.column "lifetime",   :integer
    t.column "assoc_type", :string
  end

  create_table "open_id_authentication_nonces", :force => true do |t|
    t.column "nonce",   :string
    t.column "created", :integer
  end

  create_table "open_id_authentication_settings", :force => true do |t|
    t.column "setting", :string
    t.column "value",   :binary
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "taggings", :force => true do |t|
    t.column "item_id",  :integer
    t.column "tag_id",   :integer
    t.column "tag_type", :string
  end

  add_index "taggings", ["item_id"], :name => "item_id"
  add_index "taggings", ["tag_id", "item_id"], :name => "index_taggings_on_tag_id_and_item_id"

  create_table "tags", :force => true do |t|
    t.column "parent_id", :integer
    t.column "name",      :string
    t.column "type",      :string
    t.column "data_id",   :string
    t.column "data",      :text
    t.column "synonym",   :text
  end

  add_index "tags", ["name", "type"], :name => "index_tags_on_name_and_type"

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
    t.column "activation_code",           :string,   :limit => 40
    t.column "activated_at",              :datetime
    t.column "identity_url",              :string
  end

  add_index "users", ["login"], :name => "index_users_on_login"

  add_foreign_key "accounts", ["user_id"], "users", ["id"], :name => "accounts_ibfk_1"

  add_foreign_key "items", ["account_id"], "accounts", ["id"], :name => "items_ibfk_1"

  add_foreign_key "taggings", ["item_id"], "items", ["id"], :name => "taggings_ibfk_1"
  add_foreign_key "taggings", ["tag_id"], "tags", ["id"], :name => "taggings_ibfk_2"

end
