# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 5) do

  create_table "accounts", :force => true do |t|
    t.column "user_id",     :integer
    t.column "type",        :string
    t.column "username",    :string,   :limit => 20
    t.column "password",    :string,   :limit => 20
    t.column "host",        :string,   :limit => 100
    t.column "token",       :text
    t.column "items_count", :integer,                 :default => 0
    t.column "updated_at",  :datetime
  end

  create_table "cachedalbums", :force => true do |t|
    t.column "artist",      :string
    t.column "track_title", :string
    t.column "album",       :text
  end

  create_table "items", :force => true do |t|
    t.column "account_id", :integer
    t.column "type",       :string
    t.column "time",       :datetime
    t.column "dataid",     :string
    t.column "data",       :text
    t.column "complete",   :boolean,  :default => false
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "users", :force => true do |t|
    t.column "name",            :string, :limit => 50
    t.column "hashed_password", :string
    t.column "salt",            :string
  end

end
