#!/usr/bin/env ruby

####################
#
# $LastChangedDate$
# $Rev$
# by $Author$

require 'rubygems'
require 'daemons'
require 'yaml'

class Hash
   def with_symbols!
      self.keys.each{|key| self[key.to_s.to_sym] = self[key] }; self
   end
end

options = YAML.load_file( File.dirname(__FILE__) + "/../config/daemons.yml" ).with_symbols!
options[:dir_mode] = options[:dir_mode].to_sym

Daemons.run File.dirname(__FILE__) + '/../lib/daemons/fetch_items.rb', options